# Generated by Django 3.1 on 2020-08-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='location',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Location'),
        ),
    ]
